### ISSUE TITLE
Critical log level

### ISSUE THREAD

**Issue by aujjwal-redhat** [srijan-sivakumar/antContainer#1]
Is `critical` required in log level validation?
```
valid_log_level = ['I', 'D', 'W', 'E']
log_level_dict = {'I':logging.INFO, 'D':logging.DEBUG, 'W':logging.WARNING,
                      'E':logging.ERROR}
```

**Comment by schaffung** [comment]
Yes..I might've missed that.

**Comment by schaffung** [comment]
Wait. I think this issue pertains to the remote command executioner..I'll close the issue here. I think it can be opened there.

**Comment by aujjwal-redhat** [comment]
> Wait. I think this issue pertains to the remote command executioner..I'll close the issue here. I think it can be opened there.

Yeah it's part of remote command executioner.
